#!/usr/bin/env bash
# script that doubles the number of webservers and adds new configs

apt-get  update
apt-get -y install nginx

custom_header="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
sudo systemctl restart nginx
